### PR TITLE
Support for netstandard1.0

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Review by niemyjski — APPROVED** [review]
LGTM

**Comment by mqudsi** [comment]
Thanks for this pull request. If there's no actual dependency on .NET Standard 1.3, there's no reason to require it - we do support .NET Framework 2.0 in the first place. 

However please note that the `PackageReleaseNotes` field in the project must remain cumulative as NuGet does not aggregate release notes across versions. Can you please update that to retain the old history, keep the formatting consistent (`version number: feature`), and fix the capitalization of '.NET Standard`?

Thanks.

**Comment by StefH** [comment]
Code review done.

Note that for release notes I use `GitReleaseNotes.exe` which can generate a changelog like this one: https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/CHANGELOG.md

**Comment by mqudsi** [comment]
Thanks! With regards to the release notes - thanks for the GitReleaseNotes.exe tip, I hadn't come across it before. We usually use Jira for our larger projects which can export a changelog from the tickets rather than the commits, which avoids having to sift through the commits to identify which should be in the changelog and which shouldn't (refactoring, multiple commits for one feature, etc).

Adding a `CHANGELOG.md` file is a good idea, but the real problem is that NuGet doesn't pull that info so if the user wants to upgrade a package via the Visual Studio package manager all they'll see is a link to the changelog and no info in-place, from experience a lot of users won't bother to click on that.

**Comment by niemyjski** [comment]
I never really look at the changelog.md or the release notes of nuget packages because they are always out of date. What I look at is the GitHub release section :)

**Pull request merged**
